#line 1 "C:\Users\i.kuzmychov\Code\Personal\DotAwait\DotAwait.ConsoleTest\obj\Debug\net10.0\DotAwait.ConsoleTest.GlobalUsings.g.cs"
// <auto-generated/>
global using DotAwait;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;

#line default
